USE [master]
GO
/****** Object:  Database [ProgettoCinema]    Script Date: 06/05/2022 11:34:48 ******/
CREATE DATABASE [ProgettoCinema]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProgettoCinema', FILENAME = N'D:\DATASBASE\ProgettoCinema.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProgettoCinema_log', FILENAME = N'D:\DATASBASE\ProgettoCinema_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ProgettoCinema] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProgettoCinema].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ProgettoCinema] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ProgettoCinema] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ProgettoCinema] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ProgettoCinema] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ProgettoCinema] SET ARITHABORT OFF 
GO
ALTER DATABASE [ProgettoCinema] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ProgettoCinema] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ProgettoCinema] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ProgettoCinema] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ProgettoCinema] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ProgettoCinema] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ProgettoCinema] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ProgettoCinema] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ProgettoCinema] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ProgettoCinema] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ProgettoCinema] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ProgettoCinema] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ProgettoCinema] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ProgettoCinema] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ProgettoCinema] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ProgettoCinema] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [ProgettoCinema] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ProgettoCinema] SET RECOVERY FULL 
GO
ALTER DATABASE [ProgettoCinema] SET  MULTI_USER 
GO
ALTER DATABASE [ProgettoCinema] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ProgettoCinema] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ProgettoCinema] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ProgettoCinema] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ProgettoCinema] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ProgettoCinema] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ProgettoCinema', N'ON'
GO
ALTER DATABASE [ProgettoCinema] SET QUERY_STORE = OFF
GO
USE [ProgettoCinema]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 06/05/2022 11:34:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CinemaRooms]    Script Date: 06/05/2022 11:34:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CinemaRooms](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[RoomCapacity] [tinyint] NOT NULL,
	[OccupiedSeats] [tinyint] NOT NULL,
	[CinemaId] [int] NOT NULL,
	[FilmId] [int] NOT NULL,
 CONSTRAINT [PK_CinemaRooms] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cinemas]    Script Date: 06/05/2022 11:34:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cinemas](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[Profit] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_Cinemas] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Films]    Script Date: 06/05/2022 11:34:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Films](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](max) NOT NULL,
	[Author] [nvarchar](max) NOT NULL,
	[Producer] [nvarchar](max) NOT NULL,
	[CinemaRoomId] [int] NOT NULL,
	[FilmGenreId] [int] NOT NULL,
	[Duration] [int] NOT NULL,
 CONSTRAINT [PK_Films] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GenereFilms]    Script Date: 06/05/2022 11:34:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GenereFilms](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FilmGenre] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_GenereFilms] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Persons]    Script Date: 06/05/2022 11:34:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Persons](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[Surname] [nvarchar](max) NOT NULL,
	[Birthdate] [datetime2](7) NOT NULL,
	[TicketId] [int] NOT NULL,
	[OverSeventyYear] [bit] NOT NULL,
	[UnderFiveYear] [bit] NOT NULL,
 CONSTRAINT [PK_Persons] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tickets]    Script Date: 06/05/2022 11:34:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tickets](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Seat] [int] NOT NULL,
	[Price] [decimal](18, 2) NOT NULL,
	[CinemaRoomId] [int] NOT NULL,
	[PersonId] [int] NOT NULL,
 CONSTRAINT [PK_Tickets] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_CinemaRooms_CinemaId]    Script Date: 06/05/2022 11:34:48 ******/
CREATE NONCLUSTERED INDEX [IX_CinemaRooms_CinemaId] ON [dbo].[CinemaRooms]
(
	[CinemaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_CinemaRooms_FilmId]    Script Date: 06/05/2022 11:34:48 ******/
CREATE NONCLUSTERED INDEX [IX_CinemaRooms_FilmId] ON [dbo].[CinemaRooms]
(
	[FilmId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Films_FilmGenreId]    Script Date: 06/05/2022 11:34:48 ******/
CREATE NONCLUSTERED INDEX [IX_Films_FilmGenreId] ON [dbo].[Films]
(
	[FilmGenreId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Tickets_CinemaRoomId]    Script Date: 06/05/2022 11:34:48 ******/
CREATE NONCLUSTERED INDEX [IX_Tickets_CinemaRoomId] ON [dbo].[Tickets]
(
	[CinemaRoomId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Tickets_PersonId]    Script Date: 06/05/2022 11:34:48 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Tickets_PersonId] ON [dbo].[Tickets]
(
	[PersonId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CinemaRooms]  WITH CHECK ADD  CONSTRAINT [FK_CinemaRooms_Cinemas_CinemaId] FOREIGN KEY([CinemaId])
REFERENCES [dbo].[Cinemas] ([Id])
GO
ALTER TABLE [dbo].[CinemaRooms] CHECK CONSTRAINT [FK_CinemaRooms_Cinemas_CinemaId]
GO
ALTER TABLE [dbo].[CinemaRooms]  WITH CHECK ADD  CONSTRAINT [FK_CinemaRooms_Films_FilmId] FOREIGN KEY([FilmId])
REFERENCES [dbo].[Films] ([Id])
GO
ALTER TABLE [dbo].[CinemaRooms] CHECK CONSTRAINT [FK_CinemaRooms_Films_FilmId]
GO
ALTER TABLE [dbo].[Films]  WITH CHECK ADD  CONSTRAINT [FK_Films_GenereFilms_FilmGenreId] FOREIGN KEY([FilmGenreId])
REFERENCES [dbo].[GenereFilms] ([Id])
GO
ALTER TABLE [dbo].[Films] CHECK CONSTRAINT [FK_Films_GenereFilms_FilmGenreId]
GO
ALTER TABLE [dbo].[Tickets]  WITH CHECK ADD  CONSTRAINT [FK_Tickets_CinemaRooms_CinemaRoomId] FOREIGN KEY([CinemaRoomId])
REFERENCES [dbo].[CinemaRooms] ([Id])
GO
ALTER TABLE [dbo].[Tickets] CHECK CONSTRAINT [FK_Tickets_CinemaRooms_CinemaRoomId]
GO
ALTER TABLE [dbo].[Tickets]  WITH CHECK ADD  CONSTRAINT [FK_Tickets_Persons_PersonId] FOREIGN KEY([PersonId])
REFERENCES [dbo].[Persons] ([Id])
GO
ALTER TABLE [dbo].[Tickets] CHECK CONSTRAINT [FK_Tickets_Persons_PersonId]
GO
USE [master]
GO
ALTER DATABASE [ProgettoCinema] SET  READ_WRITE 
GO
